services:
  web:
    image: node:18
    env_file:
      - web.env
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
  mysql:
    image: mysql:5.7
    env_file:
      - mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
  npm:
    image: node:18
    volumes:
      - ./:/app
    entrypoint: 'npm'
    working_dir: /app
  tests:
    image: node:18
    env_file:
      - web.env
    volumes:
      - ./:/app
    entrypoint: 'npm test'
    working_dir: /app

